import { images } from "./index";

const work = [
  {
    imgUrl: images.portfolio01,
    projectLink: "https://anas-shalaby.github.io/Education/",
    codeLink: "https://github.com/Anas-Shalaby/Education",
    name: "Education",
    title: "javascript project for schools",
    catigory: "JavaScript",
  },
  {
    imgUrl: images.portfolio02,
    projectLink: "https://anas-chat-app.herokuapp.com/",
    codeLink: "https://github.com/Anas-Shalaby/chat-app",
    name: "Chat App",
    title: "NodeJs project for chatting",
    catigory: "NodeJS",
  },
  {
    imgUrl: images.portfolio14,
    projectLink: "https://d101voff4nvgu7.cloudfront.net/",
    codeLink: "https://github.com/Anas-Shalaby/notes-app",
    name: "Notes app",
    title: "AWS project  ",
    catigory: "AWS",
  },
  {
    imgUrl: images.portfolio03,
    projectLink: "https://weather-app-anas-node.herokuapp.com/",
    codeLink: "https://github.com/Anas-Shalaby/Weather-app",
    name: "Weather App",
    title: "NodeJS project for weather",
    catigory: "NodeJS",
  },
  {
    imgUrl: images.portfolio04,
    projectLink: "https://anas-shalaby.github.io/social-media/",
    codeLink: "https://github.com/Anas-Shalaby/social-media",
    name: "Social Media",
    title: "Social Media web",
    catigory: "HTML and CSS",
  },
  {
    imgUrl: images.portfolio05,
    projectLink: "https://anas-shalaby.github.io/Special-design/",
    codeLink: "https://github.com/Anas-Shalaby/Special-design",
    name: "Special Design",
    title: "A special design",
    catigory: "JavaScript",
  },
  {
    imgUrl: images.portfolio06,
    projectLink: "https://forkify-anas.netlify.app",
    codeLink: "https://github.com/Anas-Shalaby/forkify",
    name: "Forkify",
    title: "Forkify web for food",
    catigory: "JavaScript",
  },
  {
    imgUrl: images.portfolio07,
    projectLink: "https://anas-shalaby.github.io/Mapty/",
    codeLink: "https://github.com/Anas-Shalaby/Mapty",
    name: "Mapty App",
    title: "A beautiful map web",
    catigory: "JavaScript",
  },
  {
    imgUrl: images.portfolio08,
    projectLink: " https://anas-komodi.netlify.app/",
    codeLink: "https://github.com/Anas-Shalaby/Komodi",
    name: "Komodi",
    title: "For enginner structure",
    catigory: "JavaScript",
  },
  {
    imgUrl: images.portfolio09,
    projectLink: " https://anas-shalaby.github.io/Bankist-web/",
    codeLink: "https://github.com/Anas-Shalaby/Bankist-web",
    name: "Bankist web",
    title: "A bankist web",
    catigory: "JavaScript",
  },
  {
    imgUrl: images.portfolio10,
    projectLink: "https://anas-shalaby.github.io/Bankist-project/",
    codeLink: "https://github.com/Anas-Shalaby/Bankist-project",
    name: "Bankist project",
    title: "javascript project for banks",
    catigory: "JavaScript",
  },
  {
    imgUrl: images.portfolio11,
    projectLink: "https://anas-shalaby.github.io/Omnifood/",
    codeLink: "https://github.com/Anas-Shalaby/Omnifood",
    name: "Omnifood",
    title: "A project for resturants",
    catigory: "HTML and CSS",
  },
  {
    imgUrl: images.portfolio12,
    projectLink: "https://anas-shalaby.github.io/Crazy-site/",
    codeLink: "https://github.com/Anas-Shalaby/Crazy-site",
    name: "Crazy site",
    title: "A crazy site with beautiful animation",
    catigory: "HTML and CSS",
  },
  {
    imgUrl: images.portfolio15,
    projectLink: "https://expensess-app-react.netlify.app/",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/tree/main/02-Udemy/-03-Reactjs-Maximilian/Projects/Expenses-app/Expenses-app",
    name: "Expenses App",
    title: "App with react js to practise",
    catigory: "React Js",
  },
  {
    imgUrl: images.portfolio16,
    projectLink: "https://goals-app-react.netlify.app/",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/tree/main/02-Udemy/-03-Reactjs-Maximilian/Projects/goals-app/Goals-app",
    name: "Goals app",
    title: "App with react js to practise",
    catigory: "React Js",
  },
  {
    imgUrl: images.portfolio17,
    projectLink: "https://form-react-app1.netlify.app/",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/tree/main/02-Udemy/-03-Reactjs-Maximilian/Projects/section-8-9-project",
    name: "form-react",
    title: "App with react js to practise",
    catigory: "React Js",
  },
  {
    imgUrl: images.portfolio18,
    projectLink: "https://food-order-react-app1.netlify.app/",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/tree/main/02-Udemy/-03-Reactjs-Maximilian/Projects/order-food-app/S11-project",
    name: "food-order-app",
    title: "App with react js to practise",
    catigory: "React Js",
  },
  {
    imgUrl: images.portfolio19,
    projectLink: "https://sec-12.netlify.app/",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/tree/main/02-Udemy/-03-Reactjs-Maximilian/Projects/S12-project",
    name: "Form-app",
    title: "App with react js to practise",
    catigory: "React Js",
  },
  {
    imgUrl: images.portfolio20,
    projectLink: "https://sec-react-13.netlify.app/",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/tree/main/02-Udemy/-03-Reactjs-Maximilian/Projects/S13-project",
    name: "Section 13",
    title: "App with react js to practise",
    catigory: "React Js",
  },
  {
    imgUrl: images.portfolio21,
    projectLink: "https://order-food2.web.app/",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/tree/main/02-Udemy/-03-Reactjs-Maximilian/Projects/order-food-app/S17-project",
    name: "Food-order-app-2",
    title: "App with react js to practise",
    catigory: "React Js",
  },
  {
    imgUrl: images.portfolio22,
    projectLink: "https://qoute-app-4e249.web.app/quotes",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/tree/main/02-Udemy/-03-Reactjs-Maximilian/Projects/quotes-app",
    name: "Quotes app",
    title: "App with react js to practise",
    catigory: "React Js",
  },
  {
    imgUrl: images.portfolio23,
    projectLink: "https://last-app-5697e.web.app/",
    codeLink:
      "https://github.com/Anas-Shalaby/Kalbonyan-Elmarsos/blob/main/02-Udemy/-03-Reactjs-Maximilian/Projects/Section-29",
    name: "MeetsUp-app",
    title: "App with react js to practise",
    catigory: "React Js",
  },
];

export default work;
